export const Actions = {
  UPDATE_COMMENT_SCORE: "UPDATE_COMMENT_SCORE",
  UPDATE_REPLY_SCORE: "UPDATE_REPLY_SCORE",
  ADD_REPLY: "ADD_REPLY",
  DELETE_REPLY: "DELETE_REPLY",
  EDIT_REPLY: "EDIT_REPLY",
  ADD_COMMENT: "ADD_COMMENT",
};
